### ISSUE TITLE
Gecko 4.4.4

### ISSUE THREAD

**Issue by kalpik** [darkxst/silabs-firmware-builder#116]
Hi!

Any plans for new builds? https://github.com/SiliconLabs/gecko_sdk/releases/tag/v4.4.4

Thanks!

**Comment by darkxst** [comment]
Test builds are in this branch, I will merge to main branch after some testing.
https://github.com/darkxst/silabs-firmware-builder/tree/4.4.4

**Comment by dspalu32** [comment]
zb-gw04-1v2/ncp-uart-hw-v7.4.4.0-zb-gw04-1v2-115200.gbl is working OK for me on two separate installations. Thanks!

**Comment by johnsmoses** [comment]
Hello,

Just picked up a zbdongle-e and saw the recent build. Adding devices seems to work fine and i see no issues beyond the typical route error notices that the ember driver surfaces. Not sure if this is relevant but the dongle itself crashes and resets when trying to do an ota for a single device. Not sure if super critical as repeating the updates succeeds eventually. Attaching the log in any case. 

Used: ncp-uart-hw-v7.4.4.0-zbdonglee-115200.gbl

`[2024-08-28 18:17:54] debug: 	zhc:ota:common: Payload offsets: start=39840 end=39888 dataSize=48
[2024-08-28 18:17:54] debug: 	zh:controller:endpoint: CommandResponse 0x282c02bfffeb2705/1 genOta.imageBlockResponse({"status":0,"manufacturerCode":4659,"imageType":54182,"fileVersion":268513360,"fileOffset":39840,"dataSize":48,"data":{"type":"Buffer","data":[5,144,79,154,108,6,188,135,192,70,30,241,238,11,232,41,132,0,201,32,132,0,48,101,129,96,81,160,4,144,231,157,4,238,33,192,0,52,1,160,5,161,9,162,81,163,6,144]}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"reservedBits":0,"writeUndiv":false})
[2024-08-28 18:17:54] debug: 	zh:ember: ~~~> [ZCL to=34686 apsFrame={"profileId":260,"clusterId":25,"sourceEndpoint":1,"destinationEndpoint":1,"options":4352,"groupId":0,"sequence":0} header={"frameControl":{"reservedBits":0,"frameType":1,"direction":1,"disableDefaultResponse":true,"manufacturerSpecific":false},"transactionSequenceNumber":167,"commandIdentifier":5}]
[2024-08-28 18:17:54] debug: 	zh:ember:ezsp: ===> [FRAME: ID=52:"SEND_UNICAST" Seq=145 Len=86]
[2024-08-28 18:17:54] debug: 	zh:ember:uart:ash: ---> [FRAME type=DATA frmTx=1 frmRx=1](ackRx=1)
[2024-08-28 18:17:54] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-08-28 18:17:54] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1](ackRx=1 frmTx=2)
[2024-08-28 18:17:54] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1 frmNum=1](frmRx=1) Added to rxQueue
[2024-08-28 18:17:54] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=2](ackRx=1)
[2024-08-28 18:17:54] debug: 	zh:ember:ezsp: <=== [CBFRAME: ID=69:"INCOMING_MESSAGE_HANDLER" Seq=144 Len=44]
[2024-08-28 18:17:54] debug: 	zh:ember:ezsp: ezspIncomingMessageHandler(): callback called with: [type=UNICAST], [apsFrame={"profileId":260,"clusterId":25,"sourceEndpoint":1,"destinationEndpoint":1,"options":320,"groupId":0,"sequence":185}], [packetInfo:{"senderShortId":34686,"senderLongId":"0xFFFFFFFFFFFFFFFF","bindingIndex":255,"addressIndex":255,"lastHopLqi":255,"lastHopRssi":-19,"lastHopTimestamp":0}], [messageContents=019503023312a6d35030011040980000300000]
[2024-08-28 18:17:54] debug: 	zh:controller: Received payload: clusterID=25, address=34686, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=255, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":149,"commandIdentifier":3},"payload":{"fieldControl":2,"manufacturerCode":4659,"imageType":54182,"fileVersion":268513360,"fileOffset":38976,"maximumDataSize":48},"command":{"ID":3,"response":5,"parameters":[{"name":"fieldControl","type":32},{"name":"manufacturerCode","type":33},{"name":"imageType","type":33},{"name":"fileVersion","type":35},{"name":"fileOffset","type":35},{"name":"maximumDataSize","type":32}],"name":"imageBlockRequest"}}
[2024-08-28 18:17:54] debug: 	z2m: Received Zigbee message from 'Upper Hall Outlet', type 'commandImageBlockRequest', cluster 'genOta', data '{"fieldControl":2,"fileOffset":38976,"fileVersion":268513360,"imageType":54182,"manufacturerCode":4659,"maximumDataSize":48}' from endpoint 1 with groupID 0
[2024-08-28 18:17:55] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-08-28 18:17:55] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1](ackRx=1 frmTx=2)
[2024-08-28 18:17:55] debug: 	zh:ember:uart:ash: Timer expired waiting for ACK for frmTx=2, ackRx=1
[2024-08-28 18:17:55] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=2](ackRx=1)
[2024-08-28 18:17:55] debug: 	zh:ember:uart:ash: ---> [FRAME type=DATA_RETX frmReTx=1 frmRx=2](ackRx=1 frmTx=2)
[2024-08-28 18:17:55] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-08-28 18:17:55] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1](ackRx=1 frmTx=2)
[2024-08-28 18:17:55] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=2](ackRx=1)
[2024-08-28 18:17:56] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-08-28 18:17:56] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1](ackRx=1 frmTx=2)
[2024-08-28 18:17:56] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1 frmNum=2](frmRx=2) Added to rxQueue
[2024-08-28 18:17:56] debug: 	zh:ember:uart:ash: Timer expired waiting for ACK for frmTx=2, ackRx=1
[2024-08-28 18:17:56] debug: 	zh:ember:uart:ash: ---> [FRAME type=DATA_RETX frmReTx=1 frmRx=3](ackRx=1 frmTx=2)
[2024-08-28 18:17:56] debug: 	zh:ember:ezsp: <=== [CBFRAME: ID=69:"INCOMING_MESSAGE_HANDLER" Seq=144 Len=44]
[2024-08-28 18:17:56] debug: 	zh:ember:ezsp: ezspIncomingMessageHandler(): callback called with: [type=UNICAST], [apsFrame={"profileId":260,"clusterId":25,"sourceEndpoint":1,"destinationEndpoint":1,"options":320,"groupId":0,"sequence":202}], [packetInfo:{"senderShortId":34686,"senderLongId":"0xFFFFFFFFFFFFFFFF","bindingIndex":255,"addressIndex":255,"lastHopLqi":255,"lastHopRssi":-19,"lastHopTimestamp":0}], [messageContents=01a603023312a6d350300110709b0000300000]
[2024-08-28 18:17:56] debug: 	zh:controller: Received payload: clusterID=25, address=34686, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=255, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":166,"commandIdentifier":3},"payload":{"fieldControl":2,"manufacturerCode":4659,"imageType":54182,"fileVersion":268513360,"fileOffset":39792,"maximumDataSize":48},"command":{"ID":3,"response":5,"parameters":[{"name":"fieldControl","type":32},{"name":"manufacturerCode","type":33},{"name":"imageType","type":33},{"name":"fileVersion","type":35},{"name":"fileOffset","type":35},{"name":"maximumDataSize","type":32}],"name":"imageBlockRequest"}}
[2024-08-28 18:17:56] debug: 	z2m: Received Zigbee message from 'Upper Hall Outlet', type 'commandImageBlockRequest', cluster 'genOta', data '{"fieldControl":2,"fileOffset":39792,"fileVersion":268513360,"imageType":54182,"manufacturerCode":4659,"maximumDataSize":48}' from endpoint 1 with groupID 0
[2024-08-28 18:17:57] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-08-28 18:17:57] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1](ackRx=1 frmTx=2)
[2024-08-28 18:17:57] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=3](ackRx=1)
[2024-08-28 18:17:57] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-08-28 18:17:57] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1](ackRx=1 frmTx=2)
[2024-08-28 18:17:57] debug: 	zh:ember:uart:ash: ---> [FRAME type=ACK frmRx=3](ackRx=1)
[2024-08-28 18:17:59] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA]
[2024-08-28 18:17:59] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1](ackRx=1 frmTx=2)
[2024-08-28 18:17:59] debug: 	zh:ember:uart:ash: <--- [FRAME type=DATA ackNum=1 frmNum=3](frmRx=3) Added to rxQueue
[2024-08-28 18:17:59] debug: 	zh:ember:uart:ash: Timer expired waiting for ACK for frmTx=2, ackRx=1
[2024-08-28 18:17:59] debug: 	zh:ember:uart:ash: ---> [FRAME type=DATA_RETX frmReTx=1 frmRx=4](ackRx=1 frmTx=2)
[2024-08-28 18:17:59] debug: 	zh:ember:ezsp: <=== [CBFRAME: ID=69:"INCOMING_MESSAGE_HANDLER" Seq=144 Len=44]
[2024-08-28 18:17:59] debug: 	zh:ember:ezsp: ezspIncomingMessageHandler(): callback called with: [type=UNICAST], [apsFrame={"profileId":260,"clusterId":25,"sourceEndpoint":1,"destinationEndpoint":1,"options":320,"groupId":0,"sequence":204}], [packetInfo:{"senderShortId":34686,"senderLongId":"0xFFFFFFFFFFFFFFFF","bindingIndex":255,"addressIndex":255,"lastHopLqi":255,"lastHopRssi":-19,"lastHopTimestamp":0}], [messageContents=01a803023312a6d350300110a09b0000300000]
[2024-08-28 18:17:59] debug: 	zh:controller: Received payload: clusterID=25, address=34686, groupID=0, endpoint=1, destinationEndpoint=1, wasBroadcast=false, linkQuality=255, frame={"header":{"frameControl":{"frameType":1,"manufacturerSpecific":false,"direction":0,"disableDefaultResponse":false,"reservedBits":0},"transactionSequenceNumber":168,"commandIdentifier":3},"payload":{"fieldControl":2,"manufacturerCode":4659,"imageType":54182,"fileVersion":268513360,"fileOffset":39840,"maximumDataSize":48},"command":{"ID":3,"response":5,"parameters":[{"name":"fieldControl","type":32},{"name":"manufacturerCode","type":33},{"name":"imageType","type":33},{"name":"fileVersion","type":35},{"name":"fileOffset","type":35},{"name":"maximumDataSize","type":32}],"name":"imageBlockRequest"}}
[2024-08-28 18:17:59] debug: 	z2m: Received Zigbee message from 'Upper Hall Outlet', type 'commandImageBlockRequest', cluster 'genOta', data '{"fieldControl":2,"fileOffset":39840,"fileVersion":268513360,"imageType":54182,"manufacturerCode":4659,"maximumDataSize":48}' from endpoint 1 with groupID 0
[2024-08-28 18:18:00] debug: 	zh:ember:uart:ash: <--- [FRAME type=ERROR]
[2024-08-28 18:18:00] error: 	zh:ember:uart:ash: Received ERROR from adapter, with code=ERROR_EXCEEDED_MAXIMUM_ACK_TIMEOUT_COUNT.
[2024-08-28 18:18:00] error: 	zh:ember:uart:ash: ASH disconnected | Adapter status: ASH_NCP_FATAL_ERROR
[2024-08-28 18:18:00] error: 	zh:ember:uart:ash: Error while parsing received frame, status=ASH_NCP_FATAL_ERROR.
[2024-08-28 18:18:00] error: 	zh:ember: Adapter fatal error: HOST_FATAL_ERROR
[2024-08-28 18:18:00] debug: 	zh:controller: Adapter disconnected
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash: ASH COUNTERS since last clear:
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   Total frames: RX=14386, TX=19124
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   Cancelled   : RX=0, TX=0
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   DATA frames : RX=14380, TX=4754
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   DATA bytes  : RX=348468, TX=400297
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   Retry frames: RX=4, TX=3
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   ACK frames  : RX=0, TX=14366
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   NAK frames  : RX=0, TX=0
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   nRdy frames : RX=0, TX=0
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   CRC errors      : RX=0
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   Comm errors     : RX=0
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   Length < minimum: RX=0
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   Length > maximum: RX=0
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   Bad controls    : RX=0
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   Bad lengths     : RX=0
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   Bad ACK numbers : RX=0
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   Out of buffers  : RX=0
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   Retry dupes     : RX=4
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   Out of sequence : RX=0
[2024-08-28 18:18:00] info: 	zh:ember:uart:ash:   ACK timeouts    : RX=3
[2024-08-28 18:18:09] debug: 	zh:ember:ezsp: =x=> [FRAME: ID=52:"SEND_UNICAST" Seq=145 Len=86] Error: ASH_ERROR_TIMEOUTS
[2024-08-28 18:18:09] error: 	zh:ember:ezsp: ERROR Transaction failure; status=ASH_ERROR_TIMEOUTS. Last Frame: [FRAME: ID=52:"SEND_UNICAST" Seq=144 Len=7].
[2024-08-28 18:18:09] debug: 	zh:controller:endpoint: Error: CommandResponse 0x282c02bfffeb2705/1 genOta.imageBlockResponse({"status":0,"manufacturerCode":4659,"imageType":54182,"fileVersion":268513360,"fileOffset":39840,"dataSize":48,"data":{"type":"Buffer","data":[5,144,79,154,108,6,188,135,192,70,30,241,238,11,232,41,132,0,201,32,132,0,48,101,129,96,81,160,4,144,231,157,4,238,33,192,0,52,1,160,5,161,9,162,81,163,6,144]}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"reservedBits":0,"writeUndiv":false}) failed (~x~> [ZCL to=34686] Failed to send request with status=FAIL.)
    at /app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:2515:27
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:36:20)
    at Request.func (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:728:21)
    at Request.send (/app/node_modules/zigbee-herdsman/src/controller/helpers/request.ts:82:20)
    at Endpoint.commandResponse (/app/node_modules/zigbee-herdsman/src/controller/model/endpoint.ts:723:13)
    at sendImageBlockResponse (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:601:13)
    at sendImage (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:665:34)
    at Object.updateToLatest (/app/node_modules/zigbee-herdsman-converters/src/lib/ota/common.ts:680:5)
    at OTAUpdate.onMQTTMessage (/app/lib/extension/otaUpdate.ts:268:41)
    at EventEmitter.wrappedCallback (/app/lib/eventBus.ts:174:17)
[2024-08-28 18:18:09] debug: 	zhc:ota:common: Image block response failed: Error: CommandResponse 0x282c02bfffeb2705/1 genOta.imageBlockResponse({"status":0,"manufacturerCode":4659,"imageType":54182,"fileVersion":268513360,"fileOffset":39840,"dataSize":48,"data":{"type":"Buffer","data":[5,144,79,154,108,6,188,135,192,70,30,241,238,11,232,41,132,0,201,32,132,0,48,101,129,96,81,160,4,144,231,157,4,238,33,192,0,52,1,160,5,161,9,162,81,163,6,144]}}, {"timeout":10000,"disableResponse":false,"disableRecovery":false,"disableDefaultResponse":true,"direction":1,"reservedBits":0,"writeUndiv":false}) failed (~x~> [ZCL to=34686] Failed to send request with status=FAIL.)
[2024-08-28 18:18:09] debug: 	zhc:ota:common: Update at 20.36%, remaining 648.2464401104418 seconds
[2024-08-28 18:18:09] info: 	z2m: Update of 'Upper Hall Outlet' at 20.36%, ≈ 11 minutes remaining
[2024-08-28 18:18:09] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/Upper Hall Outlet', payload '{"linkquality":255,"power_on_behavior":"off","state":"OFF","update":{"installed_version":268513281,"latest_version":268513360,"progress":20.36,"remaining":648,"state":"updating"},"update_available":null}'
[2024-08-28 18:18:09] debug: 	z2m: Saving state to file /config/zigbee2mqtt/state.json
[2024-08-28 18:18:31] info: 	zh:ember:uart:ash: Port closed.
[2024-08-28 18:18:31] info: 	zh:ember:uart:ash: ======== ASH stopped ========
[2024-08-28 18:18:31] info: 	zh:ember:ezsp: ======== EZSP stopped ========
[2024-08-28 18:18:31] info: 	zh:ember: ======== Ember Adapter Stopped ========
[2024-08-28 18:18:31] error: 	z2m: Adapter disconnected, stopping
[2024-08-28 18:18:31] debug: 	z2m: Saving state to file /config/zigbee2mqtt/state.json
[2024-08-28 18:18:31] info: 	z2m:mqtt: MQTT publish: topic 'zigbee2mqtt/bridge/state', payload '{"state":"offline"}'
[2024-08-28 18:18:31] info: 	z2m: Disconnecting from MQTT server
[2024-08-28 18:18:31] info: 	z2m: Stopping zigbee-herdsman...
[2024-08-28 18:18:31] debug: 	zh:controller:database: Writing database to '/config/zigbee2mqtt/database.db'
[2024-08-28 18:18:31] info: 	z2m: Stopped zigbee-herdsman
[2024-08-28 18:18:31] info: 	z2m: Stopped Zigbee2MQTT `
