### ISSUE TITLE
Can't flash ZBdongle E

### ISSUE THREAD

**Issue by mnlbkn** [darkxst/silabs-firmware-builder#121]
Hello,

i received my Sonoff ZBdongle E and want to use ist for zigbee2mqtt in Home Assistant. Therefor I wanted to flash via Silabs Firmware Flasher, but i always get Error messages. Drivers are installed and the device is visible in Windows device manager.
I also tried to get it in Bootloader-Mode via SecureCRT but also no Connection possible.
I've attached the Logfile from Silabs flasher.

[silabs_flasher.log](https://github.com/user-attachments/files/16906375/silabs_flasher.log)

**Comment by darkxst** [comment]
There are problems in web flasher with new ZBDongle-E stock that use cp2102 serial chip currently. I am waiting on a device to test and see if I can fix.

For the moment, use the Silabs Flasher addon in Home Assistant. There is a hidden option to provide a custom firmware link.

**Comment by Suffice** [comment]
I was able to install the firmware using Linux, but it was a bit of a pain. Ended up installing the version with the high baud rate (230400), but apparently the 115200 version is more reliable. 

Because the addon configuration file wasn't set up with the correct baud rate, I was getting errors like this in Home Assistant addon:

```
[2024-09-08 00:53:36] info: 	zh:ember:uart:ash: ======== ASH starting ========
[2024-09-08 00:53:39] error: 	z2m: Error while starting zigbee-herdsman
[2024-09-08 00:53:39] error: 	z2m: Failed to start zigbee
[2024-09-08 00:53:39] error: 	z2m: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
[2024-09-08 00:53:39] error: 	z2m: Exiting...
[2024-09-08 00:53:39] error: 	z2m: Error: Failed to start EZSP layer with status=HOST_FATAL_ERROR.
    at EmberAdapter.initEzsp (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:701:19)
    at EmberAdapter.start (/app/node_modules/zigbee-herdsman/src/adapter/ember/adapter/emberAdapter.ts:1708:24)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:138:29)
    at Zigbee.start (/app/lib/zigbee.ts:64:27)
    at Controller.start (/app/lib/controller.ts:140:27)
    at start (/app/index.js:154:5)
```

**Comment by mnlbkn** [comment]
I'm not able to get the firmware flashed via the HomeAssistant either. I also tried the 230400 baudrate version but didn't work for me.
Zigbee2MQTT doesn't work with this stick out of the box. Should it work? Maybe the Dongle is broken?
[ha_silab_log.txt](https://github.com/user-attachments/files/16921966/ha_silab_log.txt)

**Comment by darkxst** [comment]
> I'm not able to get the firmware flashed via the HomeAssistant either. I also tried the 230400 baudrate version but didn't work for me. Zigbee2MQTT doesn't work with this stick out of the box. Should it work? Maybe the Dongle is broken? [ha_silab_log.txt](https://github.com/user-attachments/files/16921966/ha_silab_log.txt)

HA flasher addon wont work with 230400 baudrate. but Z2m should work provided you set 230400 baudrate.

Web flasher currently only working on Linux or Mac for these new ZBDongle-E with cp2102 usb chips.

**Comment by mnlbkn** [comment]
Now I tried Silabs Firmware Flasher on Chromium/Ubuntu 20.04.6 LTS. 
At chrome://usb-internals the Dongle shows up correctly but the Flasher page says "no compatible devices found."
I don't know what to do anymore.

**Comment by neilime** [comment]
> Now I tried Silabs Firmware Flasher on Chromium/Ubuntu 20.04.6 LTS. At chrome://usb-internals the Dongle shows up correctly but the Flasher page says "no compatible devices found." I don't know what to do anymore.

For ubuntu, you have to allow chromium to acces your usb devices: `Settings > Apps > Chromium Web Browser > Permissions > Access USB Hardware directly`

**Comment by giandena** [comment]
Solved ! https://github.com/darkxst/silabs-firmware-builder/issues/107

**Comment by wastez** [comment]
Maybe somebody should try ember-zli with this stick to update the firmware. 
Tried it because (but with the old version of dongle e) I had problems with universal silabs flasher and it’s a really great and easy to use tool and I didn’t know it before.
